

server:
  port: 4000

auth:
  service:
    url: http://localhost:4001/auth


spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://localhost:4001
          predicates:
            - Path=/auth/**

        - id: customer-service-route
          uri: http://localhost:4002
          predicates:
            - Path=/customer/**
          filters:
            - JwtValidation

        - id: account-service-route
          uri: http://localhost:4003
          predicates:
            - Path=/account/**
          filters:
            - JwtValidation